services:
    oauth.user_provider:
        class: OAuthBundle\Provider\UserProvider
        arguments: [@doctrine.orm.entity_manager, @service_container]
    app.login_success_handler:
        class: OAuthBundle\Services\AuthenticationSuccessHandler
        arguments:  [@security.authorization_checker, @router]